stoplightio/spectral

tsconfig.json
This updates the tsconfig to not include tests or test fixtures in the JS output.
=> Dont include tests in JS output

src/rulesets/oas/index.ts
Added an api-host and api-schemes. We require these for use in the ui in lost of places so we should have a rule to enforce that
=> add api-host and api-schemes rule, update some language

package.json, src/__tests__/spectral.test.ts, src/index.ts, src/rulesets/index.ts, src/rulesets/oas/functions/oasOpSecurityDefined/index.ts, src/rulesets/oas2/index.ts, src/rulesets/oas3/index.ts, tsconfig.json, yarn.lock
Fix the original bug and did some refactoring.
The biggest change is that I removed `_paths`. It said that it tries to assure uniqueness, but the way it was implemented didn't make rules more unique than they are without paths.
Paths was a map of arrays which meant that each array could have multiple rules anyway.
The refactoring removes the redundancy and restructures the code a bit. Hopefully, simplifies it.
=> SL-787: same rules under different formats

src/__tests__/spectral.test.ts, src/rulesets/oas/functions/oasOp2xxResponse/__tests__/index.ts, src/rulesets/oas/functions/oasOpFormDataConsumeCheck/__tests__/index.ts, src/rulesets/oas/functions/oasOpIdUnique/__tests__/index.ts, src/rulesets/oas/functions/oasOpParams/__tests__/index.ts, src/rulesets/oas/functions/oasPathParam/__tests__/index.ts, src/rulesets/oas/index.ts, src/types/index.ts, yarn.lock
piped formats for common rules doesn't make sense outside of the scope of `oas2|oas3` and adds for unnecessary complexity are getting rules and format specificity. For now we are removing in favor of exact format matches to simplify logic
=> feat: remove the idea of pipes, matches on rule format should be exact

package.json, src/__tests__/spectral.test.ts, src/functions/schema.ts, src/functions/utils/ensureRule.ts, src/rulesets/oas/functions/oasOpParams/index.ts, src/rulesets/oas/functions/oasPathParam/index.ts, src/rulesets/oas/index.ts, src/rulesets/oas2/index.ts, src/rulesets/oas3/index.ts, src/types/enums.ts, src/types/index.ts, src/types/rule.ts, yarn.lock
SO-19
BREAKING CHANGE: IRuleResult extends IValidationResult which has a required `severityLabel` field.
I have updated the code to replace IRuleResult with IValidationResult. I left the original interface because it adds its own properties (and because the impact was much lower).
=> SO-19, SO-20 refactor: reuse IValidationResult

src/rulesets/oas3/__tests__/__snapshots__/api-servers.ts.snap, src/rulesets/oas3/index.ts
- n/a Docs have been added / updated (for bug fixes / features)
Bug fix
* Typo in comment (harmless). 
* OpenAPI3 test for present and non-empty `servers` array uses the word `string` instead of `array`. Associated tests therefore expect this summary value too.
The correct summary is given for the rule `api-servers`.
Possibly, if users are dependent on value of `summary` property. Users may need to update their harness code.
src/rulesets/oas3/index.ts and associated tests:
'specifcication' -> 'specification' in a comment
`servers` must be, and is tested against, being an `array` not a `string`.
=> fix: a typo and a probable cut-and-paste error (replacement for #80)

src/rulesets/oas/__tests__/__snapshots__/operation-operationId-valid-in-url.ts.snap, src/rulesets/oas/__tests__/operation-operationId-valid-in-url.ts, src/rulesets/oas/index.ts
to check for valid url characters in operationId
Bug fix (slash kind of feature).
closes #84 
No
=> fix: add operation-operationId-valid-in-url

package.json, yarn.lock
Update of jsonpath dependency.
The fix was made on jsonpath module, spectral needs to be updated because jsonpath is forked and pointed by commit sha.
Issue: https://stoplightio.atlassian.net/browse/SL-1715
No new behavior.
No
n/a
=> chore: updated jsonpath dependency

src/functions/__tests__/schema-path.test.ts, src/functions/schema-path.ts, src/rulesets/oas2/__tests__/valid-example.ts
Fixing valid-examples so that examples with $ref in it, or schemas with $ref in it, will work properly.
Running valid-example on anything with $ref in it will cause lots of warnings to be thrown to the console, and invalid examples could sneak through. 
Fixes #109
=> Fix valid-example for $ref useage

src/formatters/__tests__/json.test.ts, src/formatters/json.ts
Range and summary are included in JSON putput.
No range and summary.
No.
=> feat: include range & summary in json output

package.json, scripts/prepare-cli.js, yarn.lock
Basically, during release this runs the oclif manifest generation after the npm prepare script updates the package json version number. Should result in the appropriate version number ending up in the manifest file. Note that this is difficult to verify without actually releasing unfortunately...
=> fix: cli version mismatch on publish

src/__tests__/spectral.test.ts, src/cli/commands/lint.ts, src/linter.ts, src/runner.ts, src/spectral.ts, src/types/spectral.ts
Bug fix. This only affects our internal usage via graphite where we pass our own parsed result to `run`. Sometimes this parsed result comes from the `json` parser, which doesn't work with the `yaml` `getLocationForJsonPath` function that is currently hardcoded in spectral. This fixes that by allowing caller of `run` to pass in the appropriate `getLocationForJsonPath` function. Without this, graphite can't use spectral for json files since the json `getLocationForJsonPath` is different than the yaml `getLocationForJsonPath`.
=> fix: identify parsed result correctly

CONTRIBUTING.md
docs update
I couldn't work out how to run this tool once I had cloned the source and installed the dependencies.
The `CONTRIBUTING.md` file describes how to run from source (thanks @philsturgeon for helping me figure this out)
No
None
Also asked in the forum https://community.stoplight.io/t/contributing-to-spectral-how-to-run-from-source/597
=> docs(contributing.md): add instructions to run Spectral from source

src/cli/commands/__tests__/lint.test.ts, src/functions/alphabetical.ts, src/functions/schema-path.ts, src/linter.ts, src/rulesets/reader.ts, src/rulesets/validation.ts, src/spectral.ts
This is one of the prerequisites to merge https://github.com/stoplightio/spectral/pull/185 
We've switched to a different (ESNext) module target recently, and mixed ESM-CJS like imports are no longer valid.
=> chore: rewrite ts imports

src/functions/__tests__/schema.test.ts, src/functions/schema.ts, src/rulesets/oas3/__tests__/valid-example.ts
OpenAPI declares int64 is valid in the text doc, but formats are not defined in the OpenAPI metaschema so shoving that metaschema into a JSON Schema validator doesn't make it 100% into an OpenAPI validator as expected.
Until support is added for these OpenAPI specific formats, we are disabiling the 
error in AJV.
You get errors if you have OpenAPI specific formats in your API description documents.
We are just supressing those messages by changing AJV to ùnknownFormats: `'ignore'`.
Nope!
Discovered by @akrabat in #187.
=> fix: temporarily disable unknown format warnings

README.md, docs/config.md, docs/rulesets.md
Adding docs for the config file.
=> docs: config file

.circleci/config.yml, install.sh
This PR copies some automation I did for Prism to create and upload the artifacts on the GitHub release page and add an install.sh script for ease of consumption.
P.S: The Windows binary is broken. We need to use Azure Pipelines to produce a good one.
=> Upload artifacts on release

src/rulesets/oas3/schemas/main.json
Kinda a feature I suppose. OpenAPI v3.0 has a proper metaschema now and have done for a few months, but we're still using the one grabbed from the PR a loooong time ago.
Validates OpenAPI 3.0 description files properly I hope.
It should validate openapi 3.0 :D
=> feat: use latest openapi v3.0 metaschema

.circleci/config.yml
This will need to be tested somehow when we'll cut the real release. If you could ping me when this happens that'd be great.
=> Release only when a tag is published

package.json, src/__tests__/linter.test.ts, src/rulesets/oas2/__tests__/oas2-schema.ts, yarn.lock
Relates to #33 
**Checklist**
Yeah, I know, yet another fork, but we are quite short on time and I really doubt the PR I mentioned in #33 will be merged anytime soon. Submitting our own PR might be the best choice - I went with a slightly different implementation, so hopefully, this is accepted earlier? Not sure, I pinged all folks in that PR and let's see what their responses are.
Note on red CI checks - we seem to experience some Yarn caching issue, can anyone wipe the cache?
=> fix: use our fork of better-ajv-errors

.circleci/config.yml, package.json, scripts/inline-version.js, src/rulesets/finder.ts, yarn.lock
**Checklist**
:scream:
Let me explain...
In a browser environment without access to any kind of fs, Spectral will try to obtain rulesets from npm. This approach is fairly fine, but comes with a downside - you cannot change the location of rulesets if you don't want to break Spectral for users. This PR addresses this issue thanks to specifying the actual version of a given release.
I didn't want to rely on `package.json` on purpose - it would require `require` :laughing: or imports and so on. You know. The solution proposed here should, in theory, be more reliable.
=> build: inline pkg version

docs/migration-guides/4.0.md
=> docs: include 2.x/3.x to 4.0 migration guide

src/rulesets/oas/index.json
`paths` is a top-level property, so there is no reason to perform a deep scanning, which is utterly slow for larger specs.
=> perf: improve paths lookup

src/__tests__/linter.test.ts, src/cli/commands/__tests__/lint.test.ts, src/cli/commands/lint.ts, src/meta/rule.schema.json, src/meta/ruleset.schema.json, src/resolved.ts, src/rulesets/__tests__/__fixtures__/my-open-api-ruleset.json, src/rulesets/__tests__/lookups.spec.ts, src/rulesets/__tests__/merger.test.ts, src/rulesets/__tests__/reader.jest.test.ts, src/rulesets/__tests__/validation.test.ts, src/rulesets/lookups.ts, src/rulesets/merger.ts, src/rulesets/oas/index.json, src/rulesets/oas2/index.json, src/rulesets/oas3/index.json, src/rulesets/reader.ts, src/runner.ts, src/spectral.ts, src/types/rule.ts, src/types/ruleset.ts, src/types/spectral.ts
Closes https://github.com/stoplightio/spectral/issues/369
**Checklist**
Heads up - I haven't written any documentation yet, but if we all agree on the proposed API, I'm more than happy to give it a stab.
A few words regarding the implementation I decided to go with.
The PR features support for both of the ideas described in the linked GH issue:
- rule-scoped formats as suggested by @philsturgeon 
- ruleset-scoped formats as suggested by @P0lip
There hasn't been anything said in terms of inheritance, so I decide to keep it simple and make formats ruleset-specific, with no inheritance at all.
Moreover, I hesitated from registering any default formats such as OAS2 or OAS3 globally and made them specific to CLI version only.
I exposed 2 simple …
=> feat: register rules against specific formats

src/__tests__/linter.test.ts, src/resolved.ts, src/runner.ts, src/spectral.ts
As discussed here https://github.com/stoplightio/spectral/pull/445
**Checklist**
Initially, I thought being lenient in terms of formats matching would make sense, but once I saw the example Phil wrote in the PR above, I realized it's not really developer-friendly and does not make that much sense in the end.
=> fix: improve no matched formats case handling

src/__tests__/__fixtures__/studio-default-fixture-oas3.json, src/__tests__/linter.test.ts, src/linter.ts, src/rulesets/oas2/__tests__/oas2-schema.ts
Fixes https://github.com/stoplightio/spectral/issues/457
**Checklist**
See the issue for more info. The issue itself is fairly subtle and minor, but it's something that might introduce confusion when the linted document is huge.
=> fix: unescape json path properly

docs/guides/javascript.md, package.json, src/__tests__/__fixtures__/implicit-strings.oas3.yaml, src/__tests__/parsing.jest.test.ts, yarn.lock
Closes https://github.com/stoplightio/spectral/issues/481
**Checklist**
=> feat: YAML 1.2

package.json, src/__tests__/__fixtures__/document-with-external-refs.oas2.json, src/__tests__/__fixtures__/models/todo-full.v1.json, src/__tests__/spectral.jest.test.ts, src/resolved.ts, yarn.lock
Fixes https://github.com/stoplightio/spectral/issues/498 
**Checklist**
Discovered when working in Studio. ~It's not completed yet.~
There is still one weird issue - duplicate validation results. ~I believe my PR could have introduced it, so will fix it here.~
Nope, my code does not seem to be the cause of the issue. ~I'll file a bug report shortly.~ https://github.com/stoplightio/spectral/issues/500 it is 
~Blocked by https://github.com/stoplightio/json/pull/31~
=> fix: generate proper paths and ranges for documents with $refs

src/functions/__tests__/schema.test.ts, src/functions/schema.ts
Fixes https://github.com/stoplightio/spectral/issues/396
**Checklist**
Removes AJV warnings starting with 'unknown format'
=> fix: supress unknown format AJV error

src/rulesets/__tests__/reader.jest.test.ts
The test was non deterministic, since the functions are loaded from files and since this happens asynchronously, I could not assert the order of id  generation
=> test(reader): rewrite shakey test

package.json, src/resolvers/http-and-file.ts, yarn.lock
The code is never really executed, since we pass our own `parseResolveResult` in `Spectral#run`.
=> chore(resolver): remove redundant parseResolveResult

docs/getting-started/rulesets.md, docs/guides/cli.md
closes #559
More work needs to be done on how recommended works and is documented, because this stuff is not clear right now. This will be done as part of #447, but this will at least help in the mean time.
=> docs: missing recommended true

package.json, yarn.lock
The support for JSON pointer escape notation landed in the package. We no longer need the fork, at least for the time being
https://github.com/atlassian/better-ajv-errors/commit/2141492e306fc8742ea99a3fb4897301f7bab6f3
=> chore: switch to npm version of better-ajv-errors

src/functions/__tests__/schema.test.ts, src/functions/schema.ts, test-harness/scenarios/external-schemas-ruleset.scenario, test-harness/scenarios/rulesets/external-schemas-ruleset.yaml, test-harness/scenarios/rulesets/schemas/foo-description.yaml, test-harness/scenarios/rulesets/schemas/stoplight-title.yaml
Fixes https://github.com/stoplightio/spectral/issues/573
**Checklist**
Contains 2 unrelated fixes (see commit messages).
Regarding ajv-better-errors and the exception that's thrown - I'll try to provide a fix for the package.
This is where it fails:
https://github.com/atlassian/better-ajv-errors/blob/126ee2e45ee829e69e3b2f3f6d56eb49d5c42135/src/validation-errors/enum.js#L52
https://github.com/janl/node-jsonpointer/blob/master/jsonpointer.js#L60
Basically, jsonpointer does not expect non-object value.
=> fix(schema): support draft 6 and 7

docs/getting-started/rulesets.md, src/__tests__/linter.jest.test.ts, src/__tests__/linter.test.ts, src/__tests__/spectral.jest.test.ts, src/cli/services/linter.ts, src/formats/__tests__/json-schema.spec.ts, src/formats/__tests__/openapi.spec.ts, src/formats/index.ts, src/formats/json-schema.ts, src/formats/openapi.ts, src/index.ts, src/rulesets/evaluators.ts, src/utils/isObject.ts, test-harness/scenarios/rulesets/loose-schema-ruleset.json, test-harness/scenarios/todo-full-loose-schema.scenario
Closes https://github.com/stoplightio/spectral/issues/571
**Checklist**
<will add some>
=> feat: introduce json-schema format

docs/getting-started/rulesets.md, src/__tests__/linter.test.ts, src/resolved.ts, src/runner.ts, src/spectral.ts, src/types/spectral.ts, src/utils/__tests__/hasIntersectingElement.spec.ts, src/utils/hasIntersectingElement.ts, src/utils/index.ts
**Checklist**
Why?
Recently introduced json-schema are not mutually exclusive, meaning json-schema, json-schema-loose and json-schema-draft 4 (or any other draft) formats can be matched at the same time.
At the moment, Spectral associated a single format with a document, the first one it could match.
This is not ideal for developer experience, as you'd need to specify a couple of formats in your ruleset.
We might want to adjust the format syntax a little bit, will post a possible proposal.
Either way, allowing multiple formats to be matched should be fine enough for now.
=> feat: let multiple formats to be matched

package.json, src/functions/__tests__/schema.test.ts, src/functions/schema.ts, test-harness/scenarios/external-schemas-ruleset.scenario, yarn.lock
A follow-up PR for https://github.com/stoplightio/spectral/pull/576#discussion_r326731248
~Blocked by https://github.com/atlassian/better-ajv-errors/pull/62~
**Checklist**
=> feat(schema): improve enum validation

src/__tests__/request.jest.test.ts, src/cli/index.ts, src/fs/reader.ts, src/request.ts, test-harness/helpers.ts, test-harness/index.ts, test-harness/scenarios/proxy-agent.scenario
**Checklist**
This is almost impossible to cover with tests, as Studio has quite a specific setup. We just gotta be careful and avoid running Node specific code as much as possible.
=> fix(request): proxy-agent breaks Studio

src/__tests__/spectral.test.ts, src/linter.ts, src/resolved.ts, src/spectral.ts, src/types/spectral.ts
A small piece of $ref resolving puzzle.
This is mostly internal refactoring that does not affect any consumers, including these using their own resolvers.
=> refactor(resolving): accept any object implementing IResolver

src/cli/services/linter.ts, src/runner.ts, test-harness/scenarios/enabled-rules-amount.oas3.scenario
Closes https://github.com/stoplightio/spectral/issues/435
**Checklist**
I believe we could go even further and display the amount of skipped rules.
Thoughts?
=> feat(cli): display the amount of enabled rules

docs/guides/custom-functions.md
Adds in another example of a `.js` file that implements optional arguments in a custom function.  The example in the docs also didn't really jive with me so I felt writing one that generalized the original example (checking equality against a string) was a good natural progression.
I ran into this issue, and someone on the community forum did as well, so I figured it was worth enhancing the docs a little bit to try and help future devs, especially given custom functions are so new.
https://community.stoplight.io/t/custom-functions-for-spectral-running-locally/877
I am not a JS developer, so please let me know if something looks off or broken.  
Thoughts?
**Checklist**
=> Add in an explicit example using functionOptions in custom functions

src/functions/__tests__/alphabetical.test.ts, src/functions/alphabetical.ts
There are 3 major changes:
- no sorting - it's not really needed
- better paths are reported
- names of properties to be sorted are included in the message
=> feat(alphabetical): improve validation results

src/rulesets/oas/functions/__tests__/oasPathParam.test.ts, src/rulesets/oas/functions/oasPathParam.ts
Wanted to get my hands into that sweet open source. 
Fixes #537
**Checklist**
Some context on why some spectral messages contain new lines, asterisks, etc. The messages were originally written in markdown! This was so that we could display them nicely in Stoplight Next. I don't think this is really needed anymore with the new use case. In general the messaging syntax is still pretty ugly but at least now its consistently ugly!
=> fix: unused error format in oasPathParam rule

src/__tests__/spectral.test.ts, src/cli/services/__tests__/__fixtures__/draft-nested-ref.oas2.json, src/cli/services/__tests__/__fixtures__/refs/paths.json, src/cli/services/__tests__/linter.test.ts, src/linter.ts, src/resolved.ts, src/rulesets/oas/functions/refSiblings.ts, src/utils/hasRef.ts, src/utils/index.ts
Fixes https://github.com/stoplightio/spectral/issues/572#issuecomment-536019623 and a potential issue (see https://github.com/stoplightio/spectral/commit/28f8b65ce3504abed49f38727b921c01ab0cf496)
**Checklist**
=> fix(resolving): detect the source of local references properly

package.json, test-harness/index.ts
**Checklist**
- [N/A] Tests added / updated
- [N/A] Docs added / updated
Testing some new scenarios locally, I ran across this bug where the linux binary is hard coded in the test-harness. This adds an OS check via `process.os()` [docs](https://nodejs.org/api/os.html#os_os_platform), which should resolve as "darwin" on OSX, and fallback to linux otherwise.
I didn't see a Windows binary being created, so I believe this should cover both scenarios. Linting passed, but unsure of if/how to test. Please let me know if there is anything else I can do to help here, and thank you for taking a look!
=> Adds OS check to import of os-dependent binary in test-harness

.circleci/config.yml
Mac binary aren't getting generated because of the automatic command taking in consideration only the current machine; we need them for MacOs as well and so we'll use a custom one.
=> build: create macOS binary

.editorconfig
Helps maintaining the code style across IDEs
cf. https://editorconfig.org/
**Checklist**
While working on #635 I noticed that my IDE (VSCode) insisted on trying to format files with four spaces.
This file combined with the VSCode extension (https://editorconfig.org/#download) helps keeping the code style tamed.
=> chore: keep the indentation style homogeneous accross IDEs

package.json
**Checklist**
While working on #635, I had to add a property to `IFunctionValues`. 
`yarn build` helped me find where I had to fix the code.
`yarn lint` was all good.
As the full test suite usually takes a long time to run on my box, I tend to only run the tests that impact the code I'm working on. And let the CI server deal with the rest.
Of course, I discovered that I had forgotten to also fix some tests by taking a look a the failed karma tests on the CI server.
This PR aims at reducing the feedback loop (a little) by also typechecking the tests (without emitting code) before the build _per se_. By doing so, It adds a little overhead to the build time and an additional moving piece to the pipeline.
What do you think?
=> chore: typecheck the tests before build

docs/guides/custom-functions.md
=> docs: fix typo

docs/reference/openapi-rules.md, src/__tests__/linter.test.ts, src/rulesets/oas/functions/__tests__/oasTagDefined.test.ts, src/rulesets/oas/functions/oasTagDefined.ts, src/rulesets/oas/index.json, src/rulesets/oas/index.ts, test-harness/scenarios/enabled-rules-amount.oas3.scenario, test-harness/scenarios/severity/display-warnings.oas3.scenario, test-harness/scenarios/severity/stylish-display-proper-names.scenario
This PR adds a new operation validation that reports operation tag values that are not defined in the global tags array.
This new rule is marked as "recommended" and by default produces a warning message.
- [?] Docs added / updated
Note: "CONTRIBUTING.md" does not say anything about  doc updates, so I'm not quite sure what I need to do there.
=> Add rule to detect operation tags that are not defined in global tags object

.circleci/config.yml, CHANGELOG.md, docs/guides/cli.md, src/__tests__/linter.test.ts, src/cli/commands/lint.ts, src/cli/services/__tests__/__fixtures__/openapi-3.0-valid.yaml, src/cli/services/__tests__/linter.test.ts, src/rulesets/oas/index.json, test-harness/scenarios/help-no-document.scenario, test-harness/scenarios/parameter-description-links.oas3.scenario, test-harness/scenarios/results-default-format-json-quiet.oas3.scenario, test-harness/scenarios/results-default-format-json.oas3.scenario, test-harness/scenarios/results-default-output.oas3.scenario, test-harness/scenarios/results-default.oas3.scenario, test-harness/scenarios/results-format-stylish.oas3.scenario, test-harness/scenarios/results-skip-rule.oas3.scenario, test-harness/scenarios/results-skip-rules-multiple.oas3.scenario, test-harness/scenarios/severity/display-warnings.oas3.scenario, test-harness/scenarios/severity/fail-on-error-no-error.scenario, test-harness/scenarios/severity/fail-on-error.oas3.scenario, test-harness/scenarios/severity/stylish-display-proper-names.scenario, test-harness/scenarios/valid-no-errors.oas2.scenario
Ever since the CLI was first added, the existence of _any_ results whatsoever would trigger an exit code, even if they were only info or hint. Users have requested this be fixed several times, but we could not do it as part of #368 as it would have been a breaking change. Let's merge this, and develop will be the basis of v5.0 and any other breaking changes we have to make.
=> breaking: bump default fail severity to warn

docs/getting-started/rulesets.md, setupKarma.ts, src/__tests__/spectral.jest.test.ts, src/__tests__/spectral.karma.test.ts, src/cli/services/__tests__/output.test.ts, src/rulesets/__tests__/reader.jest.test.ts, src/rulesets/mergers/__tests__/rules.jest.test.ts, src/rulesets/mergers/rules.ts, src/rulesets/severity.ts, src/types/rule.ts
Closes https://github.com/stoplightio/spectral/issues/447
**Checklist**
=> feat: rules are recommended by default

docs/reference/functions.md
=> docs: Markdown rendering error in core functions

src/cli/services/__tests__/linter.test.ts, src/cli/services/linter/utils/__tests__/deduplicateResults.spec.ts, src/cli/services/linter/utils/deduplicateResults.ts, src/formatters/__tests__/sortResults.test.ts, src/formatters/utils/sortResults.ts
From https://github.com/stoplightio/spectral/pull/681#discussion_r334885416
=> chore: extract a result sorting function

.github/workflows/automerge.yml, scripts/install.sh, yarn.lock
Note - we won't this need change for develop, as develop already generates correct binaries.
https://github.com/stoplightio/spectral/blob/develop/.circleci/config.yml#L88
Theoretically I could upload spectral-linux and let it be, but I'd rather not touch it at all.
=> build: binary install was broken for linux

.editorconfig, docs/getting-started/rulesets.md, src/__tests__/linter.test.ts, src/linter.ts, src/meta/rule.schema.json, src/runner.ts, src/types/rule.ts, test-harness/scenarios/rules-matching-multiple-places.scenario
**Checklist**
Currently we only allow a single JSON path expression to be provided at a time for each rule.
That limitation may lead to a situation where a complex json path expression needs to be provided in order to match all intended properties. In most cases, those expressions could be split into 2-3 that would be much simpler.
=> feat: arrayish given

src/rulesets/__tests__/message.spec.ts, src/rulesets/message.ts
**Checklist**
Fixes an issue where a falsy value (referenced via `{{value}}`) would not be printed in the error message.
=> fix: print falsy value in error messages

package.json, src/__tests__/linter.test.ts, test-harness/scenarios/enabled-rules-amount.oas3.scenario, test-harness/scenarios/parameter-description-links.oas3.scenario, test-harness/scenarios/parameter-description-parameters.oas2.scenario, test-harness/scenarios/parameter-description-parameters.oas3.scenario, test-harness/scenarios/severity/fail-on-error-no-error.scenario, test-harness/scenarios/severity/fail-on-error.oas3.scenario, yarn.lock
Closes https://github.com/stoplightio/spectral/issues/726
**Checklist**
=> feat: report invalid YAML mapping keys

src/rulesets/__tests__/reader.jest.test.ts, src/rulesets/mergers/__tests__/functions.jest.test.ts, src/rulesets/mergers/functions.ts
Fixes #846 
**Checklist**
https://github.com/ai/nanoid#non-secure 
Security is a not a concern for us, since we just want random IDs to be generated for custom functions.
=> fix: use non-secure version of nanoid

.github/workflows/automerge.yml
Dependabot takes care of the PRs, so there is no need for github-actions to merge the develop branch.
The history quite a mess due to that + Dependabot is broken too when such a merge commit is pushed (see https://github.com/stoplightio/spectral/pull/832#issuecomment-566085874 as one of the examples).
In general, I believe automerging PRs bumping external packages may be unsafe, i.e what if it contains malicious code? we should at least briefly examine what the changes are all about.
According to Dependabot, it can even merge the PRs for you, so we don't need that action even for an actual merging.
=> build: disable auto-merge for dependabot

.dependabot/config.yml
At the moment we try to update dependencies on a daily basis regardless of their type.
This causes a small disruption in case of certain packages, i.e. `@types/*` or `rollup`, as they are updated more frequently, therefore plenty of PRs are created.
Developer dependencies do not need to updated that often, as we usually use a small subset of their functionality and don't use them directly in a production environment, therefore as long as our own developer experience is not affected or they don't come up a significant improvement, we don't need to check for updates daily.
Production dependencies, on the other hand, are usually more important, as they contain actual bugfixes or features impacting end users. Moreover, by performing regular updates, we are less prone to be affected by …
=> build: improve Dependabot integration

test-harness/scenarios/custom-ref-resolver.scenario, test-harness/scenarios/help-no-document.scenario, test-harness/scenarios/ignored-unrecognized-format.scenario, test-harness/scenarios/parameter-description-links.oas3.scenario, test-harness/scenarios/valid-no-errors.oas2.scenario
Follow-up PR for https://github.com/stoplightio/spectral/pull/869
=> test: warn -> error

yarn.lock
Running `yarn` from develop keeps on updating the yarn.lock file with this change.
Indeed this version is required by `object.omit` package, so having this resolution added makes sense.
=> chore(yarn): add missing dependency version

docs/reference/openapi-rules.md, src/rulesets/oas/functions/oasOpSecurityDefined.ts, test-harness/scenarios/operation-security-defined.oas3.scenario, test-harness/scenarios/rulesets/operation-security-defined.oas3.yaml
Support optional authentication for rule oas3-operation-security-defined.
Fixes #892
**Checklist**
=> fix: support optional authentication for rule oas3-operation-security-defined

src/functions/__tests__/casing.test.ts, src/functions/alphabetical.ts, src/functions/casing.ts, src/functions/enumeration.ts, src/functions/length.ts, src/functions/pattern.ts, src/functions/schema-path.ts, src/functions/schema.ts, src/functions/truthy.ts, src/functions/xor.ts, src/types/rule.ts
Tries to tackle @philsturgeon 's comment @ https://github.com/stoplightio/spectral/pull/884/files/5375e91f368c107f59c09c47c65cd834ab011b35#r363666263
**Checklist**
This PR moves some type declarations back into the files that should expose them.
=> chore: reorganize rule types declaration

docs/reference/functions.md, src/functions/__tests__/casing.test.ts, src/functions/casing.ts
=> feat: Introduce optional enhancers to casing function

test-harness/helpers.ts, test-harness/index.ts, test-harness/spawn.ts
**Let's start to shine some love on Harness in Windows land.**
---
Partially address #919 
**Checklist**
While working on #939, I eventually bit the bullet and worked a bit to scratch my own itch.
This improves a bit the running of harness tests on Windows platform.
Harness tests still fail on Win, but this greatly reduce the noise in the failures.
=> chore(harness): reduce tests failures on Windows

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .gitattributes, .vscode/extensions.json, CONTRIBUTING.md
**Checklist**
- Adds recommended vscode extensions
- Adds a preconfigured Linux/node12 based development container for troubleshooting purposes
- Provides some insights to contributing to Spectral from a Windows based environment
**Note:** The changes to the `.gitattributes` files are mostly related to the container based development process where the files will be certainly checked out in a Windows based context then "shared" between the two OSes (and the fact that Linux doesn't like CRLFs at all).
=> docs(contribution): Windows based contributors developer workflow

package.json, src/__tests__/linter.test.ts, test-harness/scenarios/severity/fail-on-error.oas3.scenario, yarn.lock
Improves https://github.com/stoplightio/spectral/issues/955
Requires https://github.com/stoplightio/yaml/pull/39
**Checklist**
=> fix(yaml): change severity of YAMLIncomaptibleValue diagnostics

src/rulesets/__tests__/offline.schemas.jest.test.ts
**Checklist**
In order to prepare for `json-schema-ref-parser`, this PR should cover the _"cover the execution of the oas2 and oas3 schema rules in offline context (in order to ensure calling bundle() against the generated static assets doesn't trigger any http call)."_ part of https://github.com/stoplightio/spectral/pull/923#issuecomment-598859149
This PR also includes a test that will ensure newly added rulesets aren't overlooked.
=> chore: ensure all rulesets can be run in offline context

package.json, rollup.config.js, src/document.ts, src/functions/__tests__/alphabetical.test.ts, src/functions/__tests__/casing.test.ts, src/functions/__tests__/typedEnum.test.ts, src/functions/alphabetical.ts, src/functions/unreferencedReusableObject.ts, src/linter.ts, src/parsers/json.ts, src/parsers/types.ts, src/parsers/yaml.ts, src/types/function.ts, yarn.lock
Fixes https://github.com/stoplightio/spectral/issues/979
Requires https://github.com/stoplightio/yaml/pull/40 and https://github.com/stoplightio/json/pull/43
**Checklist**
This trick should not be required once we have a different more suited json-ref-resolver library. :D
=> fix(alphabetical): account for lost proxies

src/rulesets/evaluators.ts, test-harness/index.ts, test-harness/scenarios/require-module.scenario
Fixes https://github.com/stoplightio/spectral/issues/1026
**Checklist**
=> fix(rulesets): require node_module

docs/guides/custom-functions.md, test-harness/scenarios/custom-function-can-return-multiple-results.scenario
Fixes #1030 and #920 
**Checklist**
This attempts at documenting how to properly return multiple results from custom functions while playing nicely with the deduplication of the fringerprinting mechanism.
=> chore(doc): how to return multiple results from a function

.github/workflows/markdown-links.yml, CHANGELOG.md
develop is failing due to this github action trawling through every issue/PR link in the CHANGELOG and hitting 429 rate limiting. It's slow and usually results in a failure, so let's just hit docs/ and see if that speeds things up.
=> chore: only check docs/ markdown links

docs/guides/custom-functions.md, src/__tests__/__fixtures__/custom-functions-oas-ruleset.json, src/__tests__/__fixtures__/functions/validateBar.js, src/__tests__/linter.jest.test.ts, src/functions/index.ts, src/rulesets/__tests__/evaluators.test.ts, src/rulesets/evaluators.ts, src/spectral.ts, src/types/function.ts
Needed by https://github.com/stoplightio/spectral/issues/924
**Checklist**
Let's not expose this feature in docs.
Back in the day, @marbemac wanted to expose ajv, lodash, and other libraries used in Spectral, but I was a bit skeptical, since we'd lose a bit of flexibility and would have to be very careful when updating dependencies. For instance we couldn't change Ajv to Djv in future without making a breaking change, etc.
We could bundle Ajv, but honestly, that's rather something we should be avoiding at all costs on this occasion, as this vastly increases the size of the bundle function. Furthermore `schema` function is stable, so there is very little risk of any potential breakage in future.
What do you folks think?
=> feat: expose available functions to custom functions

src/__tests__/linter.test.ts, src/document.ts, src/spectral.ts
Needed by Studio :grin:
A tiny bug, shouldn't really affect anyone besides Studio.
**Checklist**
=> fix: set proper document source if legacy parsed result is given

.github/workflows/markdown-links.yml
Fixes incorrectly configured `folder-path` variable for [gaurav-nelson/github-action-markdown-link-check](https://github.com/gaurav-nelson/github-action-markdown-link-check)
CC: https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/24
=> Check links only for the `docs` folder

CHANGELOG.md
~Release is blocked by https://github.com/stoplightio/spectral/pull/1051~
**Checklist**
=> docs(changelog): 5.3 release

docs/guides/custom-functions.md, src/__tests__/linter.jest.test.ts, src/spectral.ts, src/types/function.ts
**Checklist**
I hope I got the documentation right :sweat_smile:
=> feat: expose cache to custom functions

src/rulesets/__tests__/reader.jest.test.ts, src/rulesets/oas/index.json, src/types/rule.ts
**Checklist**
Following a discussion in #974 about tags in rulesets, it's been realized that they're no longer used and may even be a bit confusing would someone want to get some inspiration from the oas ruleset in order to write his/her own.
Let's provide those tags a very well deserved freedom in the Great Recycle Land of Bits.
=> chore(ruleset): drop useless oas rule tags

src/__tests__/__fixtures__/recommended-ruleset.json, src/__tests__/linter.jest.test.ts, src/__tests__/spectral.jest.test.ts, src/__tests__/spectral.karma.test.ts, src/__tests__/spectral.test.ts, src/rulesets/__tests__/reader.jest.test.ts, src/rulesets/mergers/__tests__/rules.test.ts, src/rulesets/mergers/rules.ts
As of Spectral 5, all rules are recommended by default now. However, no normalization is applied to the `recommended` property (as it's done for `severity`, for instance). This PR fixes this.
Also slightly enhance the code coverage to ensure the `recommended` setting of a rule eventually leads to the rule being run or not.
**Checklist**
=> fix: ensure all rules are recommended by default

package.json, yarn.lock
Fixes https://github.com/stoplightio/spectral/issues/1097
**Checklist**
Develop is all good, as we haven't upgraded the dependencies yet (see the lockfile), but when Spectral is installed globally, it'll install any `@stoplight/{json/yaml}` packages that match at least `3.6.0` and `3.7.0` versions respectively, therefore a newer version of a particular dependency might be installed. This is the reason why it stopped working, as I've recently updated json and yaml packages to use `@stoplight/ordered-object-literal`.
Locking the dependencies should help in a shorter perspective. In a longer perspective, we need to stop using json-ref-resolver that is indirectly causing the issue here due to the usage of immer.
I'll release …
=> fix(deps): lock @stoplight/{json,yaml}

src/cli/commands/lint.ts, src/cli/services/linter/linter.ts
Proposed changes:
- Both `vscode-spectral` and `spectral-action` need to register the supported format. Rather than forcing them to copy/paste the Spectral inner code, let's export an array of supported formats/format validators.
- Exporting the `severeEnoughToFail` would allow those same projects to easily surface a parameter similar to Spectral CLI own `fail-severity` without re-implementing the filtering algorithm.
**Checklist**
=> chore: export functions to help Spectral integration

src/document.ts, src/spectral.ts
3 tests seem to fail regularly on CI (Windows).
I thought they were flaky, yet it turns out we have a minor issue here.
Minor, cause it _may_ only happen when Spectral is used programmatically and a plain string is passed to `run` & $ref resolving takes place.
**Checklist**
=> fix: normalize documentUri

package.json, rollup.config.js, scripts/generate-assets.ts, src/rulesets/asyncapi/functions/asyncApi2PayloadValidation.ts, src/rulesets/oas/functions/oasOp2xxResponse.ts, src/rulesets/oas/functions/oasOpFormDataConsumeCheck.ts, src/rulesets/oas/functions/oasOpIdUnique.ts, src/rulesets/oas/functions/oasOpParams.ts, src/rulesets/oas/functions/oasOpSecurityDefined.ts, src/rulesets/oas/functions/oasPathParam.ts, src/rulesets/oas/functions/oasTagDefined.ts, src/rulesets/oas/functions/refSiblings.ts, src/rulesets/oas/functions/typedEnum.ts, yarn.lock
**Checklist**
**Additional Context**
Compression does its job when it comes to file size, yet it obviously doesn't solve the issue with unnecessary high memory consumption in Studio.
The gain in size comes from the $ref resolver change as well as using `import type` that makes sure we do not import any code.
**Before**:
```bash
ls -lh rulesets/assets
total 1,6M
-rw-rw-r-- 1 p0lip p0lip 1,6M maj 31 22:25 assets.json
```
**Before (gzipped)**:
```bash
ls -lh rulesets/assets
total 44K
-rw-rw-r-- 1 p0lip p0lip 43K maj 31 22:25 assets.json.gz
```
**After**:
```bash
ls -lh rulesets/assets
total 324K
-rw-rw-r-- 1 p0lip p0lip  63K maj 31 22:13 assets.asyncapi.json
-rw-rw-r-- 1 p0lip p0lip 159K maj 31 22:13 assets.json
-rw-rw-r-- 1 p0lip p0lip  97K maj …
```
=> chore: generate more efficient assets

.dependabot/config.yml
**Checklist**
Weekly is still a bit too often IMHO - we still have a couple of devdep PRs to merge each Monday, and most of them could be easily updated at a later notice given they aren't production dependencies.
Unfortunately there is no bi-weekly choice, so we are left with monthly.
=> chore(deps): set monthly schedule

package.json, src/cli/services/__tests__/linter.test.ts, src/functions/__tests__/schema-path.test.ts, src/functions/__tests__/schema.test.ts, src/functions/schema.ts, src/rulesets/asyncapi/__tests__/asyncapi-headers-schema-type-object.ts, src/rulesets/asyncapi/__tests__/asyncapi-payload-default.ts, src/rulesets/asyncapi/__tests__/asyncapi-payload-examples.ts, src/rulesets/asyncapi/functions/__tests__/asyncApi2PayloadValidation.test.ts, src/rulesets/oas/__tests__/oas2-valid-definition-example.ts, src/rulesets/oas/__tests__/oas2-valid-parameter-example.ts, src/rulesets/oas/__tests__/oas3-valid-oas-parameter-example.ts, src/rulesets/oas/__tests__/oas3-valid-parameter-schema-example.ts, src/rulesets/oas/__tests__/oas3-valid-schema-example.ts, src/rulesets/oas/__tests__/templates/_oas-example.ts, src/rulesets/oas/__tests__/templates/_schema-example.ts, test-harness/scenarios/external-schemas-ruleset.scenario, test-harness/scenarios/oas3-schema.scenario, yarn.lock
Fixes #1223 #455 
Note - I'm going to publish `@stoplight/better-ajv-errors` to npm, so the git url is temporary.
**Checklist**
=> feat: use @stoplight/better-ajv-errors

src/fs/__tests__/reader.jest.test.ts
Whether it helps or not - we shall see, but I hope so.
**Checklist**
=> test(reader): try to reduce flakiness under Windows

src/functions/__tests__/pattern.test.ts, src/functions/pattern.ts, src/rulesets/__tests__/evaluators.test.ts, src/rulesets/evaluators.ts, src/spectral.ts
Leverages the cache mechanism we added back in 5.4 so that each regular expression does not to be compiled each time.
Moreover, we avoid an allocation of an array if not required.
It's not like the perf gain is huge, but it's like 2-4% on average, which is still something.
Oh, and I expose cache to built-in (core) functions, because they didn't have access to it beforehand.
**Checklist**
=> perf(pattern): improve general perf

scripts/generate-assets.ts, src/__tests__/generate-assets.jest.test.ts, src/functions/schema.ts
Fixes the issue with oas2/oas3-schema rules in Studio.
**Checklist**
Why is it broken?
Some time ago we switched from dereferencing to bundling strategy when resolving $refs in rulesets during the Spectral offline assets generation.
This had one unintended side effect - as of that change all $refs are scoped relatively to the whole document.
This causes troubles, since in certain cases such has we pass a portion of the entire ruleset.
Having rewritten inline $refs inside of functionOptions is not really desired, because we always pass a given portion of the ruleset, therefore the $refs won't be resolvable, and eventually Ajv will refuse to validate the document.
```
MissingRefError {
message: "can't resolve reference …
```
=> build(assets): $refs under functionOptions cannot be relative to the document

docs/guides/7-sharing-rulesets.md
=> Fixed typo. functionsDir instead of functionDir

package.json, src/runner/runtime.ts, yarn.lock
related to https://github.com/stoplightio/platform-internal/pull/4132
Right now I'm using a resolution to force 2.3.1 but that would break Spectral since it relied on the `createEventEmitter` hack.
**Checklist**
=> chore(deps): bump @stoplight/lifecycle

docs/reference/functions.md, src/functions/__tests__/defined.test.ts, src/functions/defined.ts
Should help with https://github.com/openapi-contrib/style-guides/issues/10
It'd be actually good if we had some support for NOT in rulesets.
**Checklist**
=> feat: implement defined function

docs/guides/3-javascript.md, src/__tests__/linter.test.ts, src/spectral.ts, src/types/spectral.ts
Adds support for looking up formats by source (filename, uri) additionally to document content.
**Checklist**
=> feat: format lookup by source

package.json, src/__tests__/linter.jest.test.ts, src/__tests__/linter.test.ts, src/functions/__tests__/defined.test.ts, src/functions/__tests__/falsy.test.ts, src/functions/__tests__/schemaPath.test.ts, src/functions/__tests__/truthy.test.ts, src/functions/defined.ts, src/functions/falsy.ts, src/functions/schema.ts, src/functions/truthy.ts, src/functions/undefined.ts, src/rulesets/__tests__/message.test.ts, src/rulesets/message.ts, src/rulesets/reader.ts, src/utils/__tests__/replacer.test.ts, src/utils/replacer.ts, yarn.lock
This would close https://github.com/stoplightio/spectral/issues/1339
**Checklist**
I'm not quite sure whether we'll want to have this in in the end.
While, I like the new syntax here, we already have these sort-of pipe operators, which are somewhat redundant as of this change. I'd rather avoid any fragmentation here, and go with a single syntax, but this would be a breaking change.
expression-eval is used, as it's slightly safer than running plain eval, as the set of operations available is strictly limited.
EDIT:
I decided to get rid of the "pipe syntax" and use functions everywhere where necessary, as this gives us more flexibility.
Luckily, we didn't document that syntax, therefore it's not a breaking change in the …
=> feat(replacer): allow code to be evaluated

package.json, src/functions/__tests__/schema.test.ts, src/rulesets/asyncapi/__tests__/asyncapi-headers-schema-type-object.ts, test-harness/scenarios/examples.oas2.scenario, test-harness/scenarios/examples.oas3.scenario, test-harness/scenarios/external-schemas-ruleset.scenario, yarn.lock
Spotted while working on https://github.com/stoplightio/spectral/issues/1353
Right now, if enum contains a null and the value does not match, an exception is thrown.
Also opened a PR to the upstream package https://github.com/atlassian/better-ajv-errors/pull/82
**Checklist**
=> fix(schema): handle non-string enum values

docs/guides/4-custom-rulesets.md, src/__tests__/linter.test.ts, src/consts.ts, src/document.ts, src/errorMessages.ts, src/meta/rule.schema.json, src/meta/ruleset.schema.json, src/meta/shared.json, src/rulesets/__tests__/__fixtures__/parser-options-ruleset.json, src/rulesets/__tests__/reader.jest.test.ts, src/rulesets/__tests__/validation.test.ts, src/rulesets/reader.ts, src/rulesets/validation.ts, src/spectral.ts, src/types/ruleset.ts, test-harness/scenarios/severity/fail-on-error.oas3.scenario
Fixes https://github.com/stoplightio/spectral/issues/1350
**Checklist**
=> feat(ruleset): introduce parser options

README.md
**Checklist**
Currently, getting started link points to `/docs/getting-started/concepts.md` which returns a `not found` error.
=> docs(readme): getting started link

docs/guides/4-custom-rulesets.md
This change improves the documentation of the `resolved` rule attribute. This attribute was called out in the custom ruleset docs, but it was nested under the top section and didn't include wording that would make it easy to find. Specifically:
- New "Resolved" section added to the guide, mimicking the "Then" and "Given" sections
- Updated "Resolved" example
- Slight modification/addition for the "Resolved" section, adding keywords like "JSON schema reference" (specifically "reference") which is what I searched for originally and couldn't find.
**Checklist**
=> Improve documentation on "resolved" rule attribute

src/rulesets/oas/__tests__/oas3-server-trailing-slash.ts, src/rulesets/oas/index.json
This PR makes a small modification to the `oas3-server-trailing-slash` rule to allow the url value to be a single slash.
According to the description of the `servers` field of an OpenAPI object in [the OpenAPI specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#oasDocument):
> the default value would be a Server Object with a url value of `/`
Since the default value for the `url` is a single slash (`/`), this should be considered a valid value and not generate a warning message.
**Checklist**
=> fix(ruleset): Allow single trailing slash for oas3 server url

docs/reference/openapi-rules.md, src/rulesets/oas/__tests__/duplicated-entry-in-enum.ts, src/rulesets/oas/index.json, test-harness/scenarios/duplicated-entry-in-enum.oas.scenario, test-harness/scenarios/enabled-rules-amount.oas3.scenario
=> Add rule to detect duplicated entry in enum

.circleci/config.yml, scripts/install.sh
Fixes #[1374](https://github.com/stoplightio/spectral/issues/1374).
**Checklist**
Implemented the fix based on @DenialAdams suggestion
Tested on Alpine Linux container, need to install the following packages for spectral to work on alpine
```
apk add libstdc++
apk add libgcc
```
=> build(installer): support for alpine linux

.circleci/config.yml, package.json, src/cli/commands/__tests__/lint.test.ts
Node 10.x goes EOL in April 2021
Prism already requires >= 12
**Checklist**
=> chore: drop support for Node 10.x

package.json, yarn.lock
Only breaking change to `proxy-agent` is the upgrade to `agent-base` v6.
Fixes #1552
See https://github.com/TooTallNate/node-proxy-agent/releases
**Checklist**
=> chore(deps): bump proxy-agent from 3.1.1 to 4.0.1

src/rulesets/oas/__tests__/duplicated-entry-in-enum.ts, src/rulesets/oas/index.json
Fixes #1571.
**Checklist**
As it's very hard to come up with a correct given expression, it seems the easiest to simply allow everything that is not an array. This rule is to detect duplicate arrays, not check whether an enum is an array, so I think the workaround is fine.
=> fix: duplicated-entry-in-enum complains about enum property in objects

package.json, yarn.lock
**Checklist**
[CVE-2021-23337](https://nvd.nist.gov/vuln/detail/CVE-2021-23337). Vulnerability in Lodash < 4.17.21, "Improper Neutralization of Special Elements used in a Command ('Command Injection')"
[Whitesource](https://www.whitesourcesoftware.com/open-source-security-lp/?utm_origin=ad&utm_from=Adwords&utm_pcampaign=fs.brand.us-ca.search&utm_gen=Searched%20Term:whitesource%20software&gclid=Cj0KCQjwyZmEBhCpARIsALIzmnLBjaw1i_YhWXADoeT0SCuxT2s8u0mvTeATJv3qGMGizg_1_KrtNOIaAhnPEALw_wcB) security tool is alerting this package as high risk due to this.
=> chore: [CVE-2021-23337] Upgrade lodash to 4.17.21

.circleci/config.yml
Moves the docker image builds from Docker Hubs CI back to Circle CI, because apparently this:
is an [ancient issue they don't care enough to fix](https://github.com/docker/hub-feedback/issues/1777#issuecomment-835426290). I've tried everything I can think of (turning off build caches, making a new branch with a different name) and no, Docker Hub is just incapable of running "git clone" on an empty directory, as incredibly logical as that behavior would seem for generating reliable, immutable builds. And no they don't let you override the git clone step in their hooks and stuff.
This is an impediment from us releasing v6 Docker images, because presumably to release v6 we'll merge `develop` into the `master` branch. At which point DockerHub will give up and say "nope, I'm broken on master …
=> chore(docker): build docker image in Circle CI

src/rulesets/oas/schemas/3.1.json, test-harness/scenarios/oas3.1/petstore.scenario
Fixes https://github.com/stoplightio/spectral/issues/1636
**Checklist**
Temporary workaround until https://github.com/ajv-validator/ajv/issues/1625 is fixed.
This PR makes it so the property gets evaluated ("type" keyword), but since every type is allowed, the behavior is almost identical to a booleanish true schema.
=> fix(oas): unevaluated x- extensions

docs/getting-started/5-asyncapi.md, docs/reference/asyncapi-rules.md
The current page yields 404 making the markdown-link-checker check fail in all PR
**Checklist**
=> docs: asyncapi spec url returns 404

docs/guides/2-cli.md, packages/cli/src/commands/lint.ts, packages/cli/src/services/config.ts, packages/cli/src/services/linter/linter.ts, test-harness/scenarios/help-no-document.scenario, test-harness/scenarios/stdin-filepath.scenario, test-harness/scenarios/strict-options.scenario, tsconfig.json
Closes https://github.com/stoplightio/spectral/issues/1001
**Checklist**
A low-hanging fruit.
We follow ESLint & Prettier here.
- ESLint
```
Using stdin:
--stdin                         Lint code provided on <STDIN> - default: false
--stdin-filename String         Specify filename to process STDIN as
```
- Prettier
```
--stdin-filepath <path>  Path to the file to pretend that stdin comes from.
```
=> feat(cli): implement --stdin-filepath flag
