stoplightio/spectral

package.json, src/rulesets/oas/functions/oasPathParam/__tests__/index.ts, src/rulesets/oas/functions/oasPathParam/index.ts, src/rulesets/oas/index.ts, yarn.lock
- Improved the validation messages associated with the path param rule.
- Removed one path param validation:
Operation level params CAN override path level params:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-4
=> Enhancement/oas path param (SL-166)

package.json, src/rulesets/oas/functions/oasOpSecurityDefined/__tests__/index.ts, src/rulesets/oas/functions/oasOpSecurityDefined/index.ts, src/rulesets/oas/index.ts, yarn.lock
=> Fix oas2 versus oas3 security schemes

src/__tests__/spectral.test.ts, src/index.ts
SL-786
- deep cloning the provided rulset
=> SL-786 fix: prevent ruleset to be mutated

.circleci/config.yml, .codeclimate.yml, package.json
[SO-15](https://stoplightio.atlassian.net/browse/SO-15)
=> [SO-15] build: add code coverage reporting and codeclimate

package.json, yarn.lock
No change - just force release because of mistake I made (using chore: instead of fix:)
No change
No
=> fix: force release with jsonpath dep updated

CONTRIBUTING.md
Docs update
There are no contribution docs right now
Nope
I'd love feedback on if this is welcoming to an outside contributor to Stoplight. I tried to add some resources to help get people up to speed and explain some of the things we do, like `yarn commit`, that might be outside of some contributor's past experiences.
=> Contribution guide ✨

package.json, yarn.lock
Bug fix, feature, or docs update
You can also link to an open issue here.
=> fix: use http for jsonpath

README.md, src/functions/__tests__/schema-path.test.ts, src/functions/__tests__/schema.test.ts, src/functions/index.ts, src/functions/schema-path.ts, src/rulesets/oas2/__tests__/valid-example.ts, src/rulesets/oas2/index.ts, src/rulesets/oas3/__tests__/valid-example.ts, src/rulesets/oas3/index.ts, src/types/enums.ts, src/types/rule.ts
If an example is provided, make sure it is valid against the schema for that property.
SL-2065
Feature
Example is pretty much ignored.
Now examples with nonsense values, formats that are not matched, etc, will product validation errors. 
This will create a breaking change if you have invalid examples, so you will want to fix the examples.
=> feat(oas): check examples are valid against their schema

src/rulesets/oas2/__tests__/valid-example.ts
More tests. 
Chatting to @casserni we had a few concerns but it turns out everything is ooookay. These tests should live in here anyhow.
=> A few more tests for valid-example

__mocks__/fs.ts, package.json, src/cli/commands/__tests__/lint.test.ts, src/cli/commands/lint.ts, yarn.lock
New feature
Output from CLI is always sent to stdout. Piping all output results in some unwanted content such as progress reports.
Adds a --option flag to the CLI.
=> SL-2198 - CLI --output option

package.json, src/__tests__/linter.test.ts, src/spectral.ts, src/types/spectral.ts, yarn.lock
This is post 2.0, most likely :)
Parsing errors are included in validation results.
Parsing errors are ignored.
=> feat: parsing errors

CONTRIBUTING.md, README.md, package.json, yarn.lock
Adds a script that lets you build a binary executable of Spectral.
=> fix: binary building

package.json, yarn.lock
Also relaxes them a little bit.
=> fix: bump @stoplight deps

src/cli/commands/__tests__/lint.test.ts
Not needed
Fixed description of the test.
I believe both the tests are having the same description while they are doing different things. Let me know if that's not the case. Cheers!
=> test(cli): changed the description for loading spec files from web

README.md
docs update
Resolves #73 
This PR adds as short YAML example to the documentation.
n/a
n/a
=> docs: adds oas yaml example

README.md
docs update
Resolves #153 
This PR adds Docker installation/usage to the documentation.
n/a
n/a
=> docs: add docker usage/installation

package.json, src/__tests__/functions.test.ts, src/__tests__/linter.test.ts, src/__tests__/spectral.test.ts, src/cli/commands/__tests__/lint.test.ts, src/cli/commands/lint.ts, src/formatters/stylish.ts, src/functions/__tests__/alphabetical.test.ts, src/functions/__tests__/enum.test.ts, src/functions/__tests__/schema-path.test.ts, src/functions/__tests__/truthy.test.ts, src/functions/schema.ts, src/linter.ts, src/rulesets/__tests__/path.unit.ts, src/rulesets/__tests__/reader.unit.ts, src/rulesets/oas/functions/oasPathParam/index.ts, src/rulesets/reader.ts, src/runner.ts, src/types/function.ts, yarn.lock
This PR is pretending to be about skip rules, because semantic bot didnt notice,
but really it is about new lint fixes after we updated stoplights tslint packages.
Bug fix, feature, or docs update
You can also link to an open issue here.
=> Skip Rules

.circleci/config.yml
Recently pkg was updated to support node 12, so this PR makes sure our tests
pass in node 12 too. 
Node 12 support uncertain.
=> feat: add support node 12

.circleci/config.yml, package.json, src/rulesets/oas/functions/oasPathParam/__tests__/__snapshots__/index.test.ts.snap, src/rulesets/oas/functions/oasPathParam/__tests__/index.test.ts, src/rulesets/oas/index.ts
addresses https://github.com/stoplightio/spectral/pull/215#pullrequestreview-239753797
removes useless docs script
You can also link to an open issue here.
Nope :)
=>  fix: improve usefulness of path-params linting messages

src/linter.ts, src/rulesets/message.ts, src/rulesets/oas/__tests__/message.spec.ts, src/rulesets/oas/index.ts, src/rulesets/oas2/index.ts, src/rulesets/oas3/index.ts, src/types/rule.ts
Different string interpolation.
The current implementation is fine, but won't work once we convert our rulesets to YAML/JSON.
There is no breaking change. Actual messages are untouched.
=> feat: change string interpolation implementation

package.json, src/config/configLoader.ts, yarn.lock
Dependency update
You can also link to an open issue here.
Tested it manually.
=> chore: bump fs-extra

src/cli/commands/__tests__/lint.test.ts, src/cli/commands/lint.ts
Fixes https://github.com/stoplightio/spectral/issues/172
Feature
We don't have a quiet switch, so there is no way to instrument Spectral to emit parseable output 
The flag is implemented
Nope, just an addition.
0.
=> feat: implement --quiet switch

README.md
Docs update
Implemented the quiet flag in #172 and got added to CLI but not the readme
=> add quiet flag to readme

package.json, src/__tests__/__fixtures__/petstore.invalid-schema.oas3.yaml, src/__tests__/linter.test.ts, src/functions/__tests__/schema-path.test.ts, src/functions/__tests__/schema.test.ts, src/functions/schema.ts, src/rulesets/oas2/__tests__/oas2-schema.ts, src/rulesets/oas2/__tests__/valid-example.ts, src/rulesets/oas3/__tests__/valid-example.ts, yarn.lock
PR attempting to fix #221.
Spectral produces unuseful schema validation messages.
We integrate better-ajv-errors, which should, in theory, filter out the messages and provide more meaningful output.
It does not.
=> feat: incorporate better-ajv-errors

src/meta/rule.schema.json, src/rulesets/__tests__/validation.test.ts
=> fix: rule with human-readable severity should be considered as valid

azure-pipelines.yml
Run azure pipeline tests on develop branch
=> test: run tests on develop branch

README.md, src/cli/commands/lint.ts, src/types/config.ts
BREAKING CHANGE: --max-results flag is gone.
**Checklist**
=> feat(cli): remove --max-results flag

package.json, src/cli/commands/__tests__/lint.test.ts, yarn.lock
**Checklist**
Yeah, I know previous looked a bit different, but it didn't make much sense.
Right now it's slightly better and what's more important consistent for both CRLF and LF line endings.
=> test(lint): revert previous assertion

src/rulesets/finder.ts, src/rulesets/severity.ts
**Checklist**
It's all about simplifying the code and satisfying CodeClimate.
Moreover, decided to left a couple of comments on each code path to make it easier to follow the execution flow in the future.
=> refactor: reduce complexity

docs/rulesets.md, src/__tests__/linter.test.ts, src/cli/commands/__tests__/lint.test.ts, src/rulesets/oas2/index.json, src/rulesets/oas3/index.json
**Checklist**
As requested by Marc :)
Note: we execute rules in order, therefore I had to update the tests to reflect the changes.
=> docs(rulesets): rename OAS to OpenAPI

docs/rulesets.md
Summary property was removed in 4.x
=> docs(rulesets): summary -> message

docs/js-api.md
=> docs(js-api): update rulesets import

package.json, yarn.lock
Fixes #385
**Checklist**
We shall publish a patch version once the fix provided in the following PR proves to solve the issue.
=> fix: bump better-ajv-errors

CHANGELOG.md, package.json, yarn.lock
Two reviews required as this is going to master.
=> Release v4.0.1

pets-mini.yaml, src/cli/commands/__tests__/lint.test.ts, src/functions/__tests__/falsy.test.ts, src/functions/falsy.ts, src/functions/index.ts, src/functions/undefined.ts, src/rulesets/oas2/__tests__/oas2-anyOf.ts, src/rulesets/oas2/__tests__/oas2-oneOf.ts, src/rulesets/oas2/index.json, src/rulesets/oas3/index.json
=> new rule: no anyOf & oneOf in OpenAPI v2

src/rulesets/__tests__/__fixtures__/github-issue-447-fixture.yaml, src/rulesets/__tests__/reader.jest.test.ts
https://github.com/stoplightio/spectral/issues/447
=> test: cover #447

docs/reference/openapi-rules.md, src/rulesets/oas/__tests__/no-eval-in-markdown.ts, src/rulesets/oas/__tests__/path-declarations-must-exist.ts, src/rulesets/oas/functions/oasPathParam.ts, src/rulesets/oas/index.json
=> docs: openapi rules

package.json, scripts/compile-rulesets.js, src/cli/commands/lint.ts, src/fs/reader.ts, src/index.ts, src/rulesets/__tests__/reader.jest.test.ts, src/rulesets/__tests__/validation.test.ts, src/rulesets/evaluators.ts, src/rulesets/loader.ts, src/rulesets/mergers/__tests__/functions.jest.test.ts, src/rulesets/mergers/functions.ts, src/rulesets/reader.ts, src/rulesets/validation.ts, src/spectral.ts, src/types/ruleset.ts, yarn.lock
Closes https://github.com/stoplightio/spectral/issues/494
**Checklist**
Everything can be found in https://github.com/stoplightio/spectral/issues/494
=> feat: transferable rulesets

src/rulesets/__tests__/__fixtures__/simple-disable-ruleset.yaml, src/rulesets/__tests__/reader.jest.test.ts, src/rulesets/mergers/rules.ts
**Checklist**
I had a fix for that a few days ago, but simply forgot to commit it and push. Silly me.
=> fix(rulesets): false severity should always be respected

.dockerignore, Dockerfile
Copy necessary files + make the Docker check required
=> fix: copy rollup files for docker image

src/rulesets/validation.ts
=> chore(validation-error): make ajv errors public

src/functions/schema.ts
=> fix: do not use tslint in production

src/formatters/__tests__/__fixtures__/mixed-errors-with-different-paths.json, src/formatters/__tests__/junit.test.ts, src/formatters/junit.ts, test-harness/scenarios/results-format-junit.oas3.scenario
Relates to https://github.com/stoplightio/spectral/issues/572
**Checklist**
=> feat(junit): include property path

src/formatters/__tests__/junit.test.ts, src/formatters/junit.ts, test-harness/scenarios/results-format-junit.oas3.scenario
Fixes https://github.com/stoplightio/spectral/issues/607
**Checklist**
Let's double-check whether everything is alright this time around.
=> fix(junit): make formatter more spec-compliant

test-harness/README.md, test-harness/index.ts
**Checklist**
- [N/A] Tests added / updated
- [N/A] Docs added / updated
As documented and implemented, it is possible to receive false negatives in test scenarios where results of the `command` return no response (particularly when using grep). Consider the following scenario from the [example](https://github.com/stoplightio/spectral/tree/develop/test-harness#a-real-example)
```
====test====
Hello
====document====
openapi: 3.0.2
paths:
/todos:
get:
responses:
200:
description: Get Todo Items
content:
'application/json':
example: hello
====command====
lint {document} | grep "something"
====stdout====
2:6  warning  some-rule  This rule is complaining about something.
```
One would expect this scenario as-is to fail, as …
=> In test-harness scenarios that expect a stdout, always check against actual stdout

docs/guides/cli.md, docs/guides/workflows.md
=> docs(cli): expose multiple paths

package.json, yarn.lock
=> chore(deps): remove @types/yaml

docs/reference/openapi-rules.md, src/__tests__/linter.test.ts, src/rulesets/__tests__/rule_name_conflicts.jest.test.ts, src/rulesets/oas2/__tests__/model-description.ts, src/rulesets/oas2/index.json, src/rulesets/oas3/__tests__/model-description.ts, src/rulesets/oas3/index.json, test-harness/scenarios/enabled-rules-amount.oas3.scenario
Fixes #670
**Checklist**
This proposed change also contains a test to ensure this kind of name collision won't happen again in the future.
=> fix(rule): workaround 'model-description' rule name collision

src/functions/xor.ts
Describe the xor contract in a more explicit manner.
**Checklist**
=> fix: refine xor function error message

CONTRIBUTING.md
This PR makes a few small additions to the `CONTRIBUTING.md` file.  These are items that would have helped me avoid some rework on my first PR to Spectral.
=> docs: Minor additions to CONTRIBUTING.md.

src/cli/services/__tests__/linter.test.ts, src/cli/services/linter/utils/__tests__/listFiles.spec.ts, src/cli/services/linter/utils/listFiles.ts
Fixes https://github.com/stoplightio/spectral/issues/679
**Checklist**
cc @nulltoken, I gave it a try manually under Windows using Powershell and it did the trick, but since I'm certainly more of a Unix guy, so if you'd like to verify it on your own and see if you are issues are gone, you are more than welcome to do so.
=> fix: unixify glob patterns

package.json, src/__tests__/spectral.jest.test.ts, src/__tests__/spectral.test.ts, src/rulesets/__tests__/reader.jest.test.ts, yarn.lock
=> chore: Upgrade to typescript 3.7.2

src/cli/services/linter/utils/__tests__/listFiles.spec.ts
Closes https://github.com/stoplightio/spectral/issues/748
**Checklist**
=> test: stub fast-glob more properly

README.md
These old badges weren't doing much of use and the planet is more important.
=> Offset.Earth Badge

docs/guides/javascript.md
See discussion in https://github.com/stoplightio/spectral/issues/717
**Checklist**
=> docs: describe custom resolver usage

src/cli/commands/__tests__/lint.test.ts, src/cli/commands/lint.ts, src/cli/services/linter/linter.ts, src/cli/services/linter/utils/listFiles.ts, src/fs/__tests__/__fixtures__/simple, src/fs/__tests__/reader.jest.test.ts, src/fs/reader.ts, test-harness/scenarios/help-no-document.scenario, test-harness/scenarios/stdin-document-with-errors.scenario, test-harness/scenarios/stdin.scenario
Closes #757
**Checklist**
~Added isTTY env variable.
https://github.com/stoplightio/spectral/tree/chore/test-harness work has been pushed here. Still need to handle tty correctly, but it's getting closed.~
=> feat(cli): accept stdin

test-harness/README.md, test-harness/index.ts, test-harness/scenarios/enabled-rules-amount.oas3.scenario, test-harness/scenarios/external-schemas-ruleset.scenario, test-harness/scenarios/help-no-document.scenario, test-harness/scenarios/parameter-description-links.oas3.scenario, test-harness/scenarios/parameter-description-parameters.oas2.scenario, test-harness/scenarios/parameter-description-parameters.oas3.scenario, test-harness/scenarios/proxy-agent.scenario, test-harness/scenarios/results-default-format-json-quiet.oas3.scenario, test-harness/scenarios/results-default-format-json.oas3.scenario, test-harness/scenarios/results-default-output.oas3.scenario, test-harness/scenarios/results-default.oas3.scenario, test-harness/scenarios/results-format-junit.oas3.scenario, test-harness/scenarios/results-format-stylish.oas3.scenario, test-harness/scenarios/results-skip-rule.oas3.scenario, test-harness/scenarios/results-skip-rules-multiple.oas3.scenario, test-harness/scenarios/severity/display-errors.oas3.scenario, test-harness/scenarios/severity/display-warnings.oas3.scenario, test-harness/scenarios/severity/fail-on-error-no-error.scenario, test-harness/scenarios/severity/fail-on-error.oas3.scenario, test-harness/scenarios/severity/stylish-display-proper-names.scenario, test-harness/scenarios/stdin-document-with-errors.scenario, test-harness/scenarios/stdin.scenario, test-harness/scenarios/todo-full-loose-schema.scenario, test-harness/scenarios/valid-no-errors.oas2.scenario
Addressing feedback Vincenzo and Phil left in the original PR https://github.com/stoplightio/spectral/pull/766
=> chore(test-harness): update readme

package.json, src/cli/services/linter/linter.ts, src/functions/__tests__/alphabetical.test.ts, src/index.ts, src/parsers/index.ts, src/parsers/json.ts, src/parsers/yaml.ts, src/spectral.ts, test-harness/scenarios/alphabetical-responses-order.oas3.scenario, yarn.lock
Fixes https://github.com/stoplightio/spectral/issues/730
**Checklist**
=> fix: preserve order of properties

docs/getting-started/openapi.md, docs/getting-started/rulesets.md, docs/guides/custom-functions.md
=> docs: added missing functions: [abc]

.github/workflows/markdown-links.yml
https://github.com/planetscale/github-action-markdown-link-check/pull/1
=> chore: fixing markdown link checker

CHANGELOG.md
Blocked by https://github.com/stoplightio/spectral/pull/1008
**Checklist**
=> docs(changelog): 5.2 release

docs/reference/functions.md
=> docs: truthy example

setupKarma.ts
Lesson learned from #974: Don't get bad karma, it will come with a revenge.
This should save some time to the next developer who will work in this area by providing a meaningful message to the help the poor soul.
**Checklist**
=> chore(karma): Provide actionable developer feedback

__mocks__/nanoid/non-secure.ts, package.json, src/rulesets/__tests__/reader.jest.test.ts, src/rulesets/mergers/__tests__/functions.jest.test.ts, yarn.lock
=> test(jest): nanoid mock

docs/getting-started/rulesets.md, src/__tests__/__fixtures__/custom-oas-ruleset.json, src/__tests__/linter.jest.test.ts, src/__tests__/spectral.jest.test.ts, src/linter.ts, test-harness/scenarios/exceptions.circular.reference.oas3.scenario, test-harness/scenarios/exceptions.circular.silenced.oas3.scenario
Fix #1018
**Checklist**
/cc @m-mohr
=> fix(exceptions): avoid swallowing results

src/rulesets/oas/__tests__/info-license.ts, src/rulesets/oas/index.json
**Checklist**
Discovered while working on #974
=> fix(ruleset): Correct misleading 'info-license' message

README.md
**Checklist**
> If indicated yes above, please describe the breaking change(s).
>
> **Remove this quote before creating the PR.**
If applicable, add screenshots or gifs to help demonstrate the changes. If not applicable, remove this screenshots section before creating the PR.
Add any other context about the pull request here. Remove this section if there is no additional context.
=> Updating the Treeware link, text and badge

src/rulesets/oas/__tests__/openapi-tags.ts, src/rulesets/oas/index.json
Should help this rule fulfill its own promise ;-)
**Checklist**
Discovered while working on #974
=> fix(ruleset): Make openapi-tags rule fit its description

README.md
**Checklist**
> If indicated yes above, please describe the breaking change(s).
>
> **Remove this quote before creating the PR.**
If applicable, add screenshots or gifs to help demonstrate the changes. If not applicable, remove this screenshots section before creating the PR.
Add any other context about the pull request here. Remove this section if there is no additional context.
=> chore: adding Treeware Tree badge

scripts/install.sh
Fixes #1057
**Checklist**
> If indicated yes above, please describe the breaking change(s).
>
> **Remove this quote before creating the PR.**
If applicable, add screenshots or gifs to help demonstrate the changes. If not applicable, remove this screenshots section before creating the PR.
Add any other context about the pull request here. Remove this section if there is no additional context.
=> fix: install.sh script not working for linux

package.json
cf. https://github.com/okonet/lint-staged/pull/724
**Checklist**
=> chore(lint): resolve lint-staged deprecation warning

src/functions/schema.ts
Helps with https://github.com/stoplightio/spectral/pull/974/files#r410127724
**Checklist**
Example usage:
```ts
export default function(this: IFunctionContext, targetVal, opts, paths, otherValues) {
const { schema } = this.functions;
const ajv = schema.createAJvInstance({
// whatever ajv options
});
// specs can be accessed as follows
ajv.addSchema(schema.specs.v7);
// if you want to perform validation...
schema.call(this, targetVal, { ...opts, ajv: ajv.validate }, paths, otherValues);
}
```
Didn't test it on my own, but should work TM. :crossed_fingers:
=> chore(schema): expose some extras

docs/guides/6-exceptions.md
=> chore(doc): fix `except` example

src/cli/services/linter/linter.ts, src/formats/consts.ts, src/formats/index.ts
Addresses my comment in https://github.com/stoplightio/spectral/pull/1134
**Checklist**
=> chore: export known formats in main entrypoint

docs/guides/6-exceptions.md
=> Add a longer path example for the except docs

src/__tests__/linter.test.ts, src/runner/runner.ts
Fixes https://github.com/stoplightio/spectral/issues/1170
**Checklist**
=> fix: handle exceptions thrown by runRule

package.json
Windows doesn't know about shebang ;-)
**Checklist**
=> chore: x-platify 'inline-version' yarn script

scripts/inline-version.js, src/consts.ts, src/index.ts, src/rulesets/finder.ts
=> chore: expose Spectral version

src/__tests__/linter.test.ts, src/documentInventory.ts, src/functions/unreferencedReusableObject.ts, src/runner/runner.ts
Fixes https://github.com/stoplightio/spectral/issues/1209
**Checklist**
=> fix: do not attempt to resolve primitive values

README.md
=> chore(readme): apache license 2.0 is used

README.md
=> docs: update treeware wording

docs/reference/openapi-rules.md, src/rulesets/oas/functions/__tests__/oasPathParam.test.ts, src/rulesets/oas/functions/oasPathParam.ts
Fixes #1187.
**Checklist**
> If indicated yes above, please describe the breaking change(s).
>
> **Remove this quote before creating the PR.**
If applicable, add screenshots or gifs to help demonstrate the changes. If not applicable, remove this screenshots section before creating the PR.
Add any other context about the pull request here. Remove this section if there is no additional context.
=> fix: check against valid operations before checking parameters exist.

scripts/generate-assets.ts, src/cli/services/linter/utils/getRuleset.ts, src/formats/consts.ts
=> chore: export KNOWN_RULESETS

package.json, yarn.lock
=> chore(deps): bump @stoplight/{json-ref-resolver,json}

CHANGELOG.md
Hopefully I didn't miss anything.
**Checklist**
=> docs(changelog): release 5.5

docs/guides/4-custom-rulesets.md
The paragraph describe how to extend a rulesets not a rule.
=> Fixed section title

src/rulesets/__tests__/__fixtures__/ruleset-with-merge-keys.yaml, src/rulesets/__tests__/reader.jest.test.ts, src/rulesets/reader.ts
Closes https://github.com/stoplightio/spectral/issues/1325
**Checklist**
=> feat(ruleset): support YAML merge keys

README.md
This PR fixes a few broken links pointing to an old version of the documentation.
=> docs(readme): invalid documentation links

docs/guides/3-javascript.md, docs/reference/yaml.md
Closes https://github.com/stoplightio/spectral/issues/1345
**Checklist**
=> docs: move a note on YAML to a separate document

CHANGELOG.md
=> docs(changelog): release 5.6

docs/guides/5-custom-functions.md
Fixes https://github.com/stoplightio/spectral/issues/1335
Fixes https://github.com/stoplightio/spectral/issues/1275
**Checklist**
=> docs(custom-functions): update otherValues & add info about core fns

src/rulesets/oas/__tests__/oas3-valid-media-example.test.ts, src/rulesets/oas/functions/oasExample.ts
Fixes https://github.com/stoplightio/spectral/issues/1349
**Checklist**
=> fix(oas-valid-example): ignore externalValue

package.json, patches/ajv+6.12.5.patch, src/functions/__tests__/schema.test.ts, src/functions/schema.ts, src/rulesets/oas/__tests__/typed-enum.ts, src/rulesets/oas/functions/typedEnum.ts, yarn.lock
Fixes https://github.com/stoplightio/spectral/issues/1359
**Checklist**
=> feat(schema): supports x-nullable for OAS2

CHANGELOG.md
=> docs(changelog): release 5.7

CHANGELOG.md
**Checklist**
@philsturgeon I'm going to merge it right away, since there isn't much to do here, but feel free to take a look at it at your leisure.
=> docs(changelog): release 5.7.2

CHANGELOG.md
=> docs(changelog): release 5.8

src/__tests__/generate-assets.jest.test.ts, src/__tests__/linter.test.ts, src/cli/formatters/__tests__/pretty.test.ts, src/cli/services/__tests__/linter.test.ts, src/functions/__tests__/schema.test.ts, src/functions/__tests__/schemaPath.test.ts, src/functions/schema.ts, src/rulesets/asyncapi/__tests__/asyncapi-headers-schema-type-object.ts, src/rulesets/asyncapi/__tests__/asyncapi-payload-default.ts, src/rulesets/asyncapi/__tests__/asyncapi-payload-examples.ts, src/rulesets/asyncapi/__tests__/asyncapi-payload.ts, src/rulesets/asyncapi/__tests__/asyncapi-schema-default.ts, src/rulesets/asyncapi/__tests__/asyncapi-schema-examples.ts, src/rulesets/asyncapi/__tests__/asyncapi-schema.ts, src/rulesets/asyncapi/functions/__tests__/asyncApi2PayloadValidation.test.ts, src/rulesets/asyncapi/index.json, src/rulesets/oas/__tests__/duplicated-entry-in-enum.ts, src/rulesets/oas/__tests__/oas2-schema.ts, src/rulesets/oas/__tests__/oas2-valid-media-example.ts, src/rulesets/oas/__tests__/oas2-valid-schema-example.ts, src/rulesets/oas/__tests__/oas3-valid-media-example.test.ts, src/rulesets/oas/__tests__/oas3-valid-schema-example.ts, src/rulesets/oas/__tests__/valid-example.test.ts, src/rulesets/oas/functions/__tests__/oasDocumentSchema.test.ts, test-harness/scenarios/duplicated-entry-in-enum.oas.scenario, test-harness/scenarios/examples.oas2.scenario, test-harness/scenarios/examples.oas3.scenario, test-harness/scenarios/external-schemas-ruleset.scenario, test-harness/scenarios/oas2-valid-media-example.oas2.scenario, test-harness/scenarios/oas3-schema.scenario
The purpose of the following PR is to simplify the review process of https://github.com/stoplightio/spectral/pull/1584
**Checklist**
=> chore(schema): reword "should" to "must"

docs/migration-guides/6.0.md
Needed for https://github.com/stoplightio/platform-internal/issues/6188
**Checklist**
=> docs(migration-guide): better coverage

docs/getting-started/2-installation.md
=> docs: drop githack.com

packages/cli/src/services/linter/utils/getRuleset.ts, packages/ruleset-migrator/package.json, packages/ruleset-migrator/scripts/generate-test-fixtures.ts, packages/ruleset-migrator/src/__tests__/__fixtures__/exceptions-variant-1/output.cjs, packages/ruleset-migrator/src/__tests__/__fixtures__/exceptions-variant-1/output.mjs, packages/ruleset-migrator/src/__tests__/__fixtures__/exceptions-variant-1/ruleset.yaml, packages/ruleset-migrator/src/__tests__/__fixtures__/extends-variant-5/assets/ruleset.yaml, packages/ruleset-migrator/src/__tests__/__fixtures__/extends-variant-5/output.cjs, packages/ruleset-migrator/src/__tests__/__fixtures__/extends-variant-5/output.mjs, packages/ruleset-migrator/src/__tests__/__fixtures__/extends-variant-5/ruleset.yaml, packages/ruleset-migrator/src/__tests__/__fixtures__/functions-variant-1/output.cjs, packages/ruleset-migrator/src/__tests__/__fixtures__/functions-variant-1/output.mjs, packages/ruleset-migrator/src/__tests__/__fixtures__/functions-variant-2/output.cjs, packages/ruleset-migrator/src/__tests__/__fixtures__/functions-variant-2/output.mjs, packages/ruleset-migrator/src/__tests__/ruleset.test.ts, packages/ruleset-migrator/src/index.ts, packages/ruleset-migrator/src/transformers/except.ts, packages/ruleset-migrator/src/transformers/extends.ts, packages/ruleset-migrator/src/transformers/functions.ts, packages/ruleset-migrator/src/transformers/index.ts, packages/ruleset-migrator/src/transformers/rules.ts, packages/ruleset-migrator/src/tree/commonjs.ts, packages/ruleset-migrator/src/tree/esm.ts, packages/ruleset-migrator/src/tree/index.ts, packages/ruleset-migrator/src/tree/types.ts, packages/ruleset-migrator/src/types.ts, packages/ruleset-migrator/src/validation/schema.ts, packages/ruleset-migrator/src/validation/types.ts, tsconfig.json
Closes https://github.com/stoplightio/platform-internal/issues/6969
**Checklist**
=> feat(ruleset-migrator): inline external rulesets & support exceptions 

packages/rulesets/src/asyncapi/__tests__/asyncapi-channel-no-empty-parameter.test.ts, packages/rulesets/src/asyncapi/__tests__/asyncapi-channel-no-query-nor-fragment.test.ts, packages/rulesets/src/asyncapi/__tests__/asyncapi-channel-no-trailing-slash.test.ts, packages/rulesets/src/asyncapi/__tests__/asyncapi-headers-schema-type-object.test.ts, packages/rulesets/src/asyncapi/__tests__/asyncapi-info-contact-properties.test.ts, packages/rulesets/src/asyncapi/__tests__/asyncapi-info-contact.test.ts, packages/rulesets/src/asyncapi/__tests__/asyncapi-info-description.test.ts, packages/rulesets/src/asyncapi/__tests__/asyncapi-info-license-url.test.ts, packages/rulesets/src/asyncapi/__tests__/asyncapi-info-license.test.ts, packages/rulesets/src/asyncapi/__tests__/asyncapi-operation-description.test.ts, packages/rulesets/src/asyncapi/__tests__/asyncapi-operation-operationId.test.ts, packages/rulesets/src/asyncapi/__tests__/asyncapi-parameter-description.test.ts, packages/rulesets/src/asyncapi/__tests__/asyncapi-payload-unsupported-schemaFormat.test.ts, packages/rulesets/src/asyncapi/__tests__/asyncapi-server-no-empty-variable.test.ts, packages/rulesets/src/asyncapi/__tests__/asyncapi-server-no-trailing-slash.test.ts, packages/rulesets/src/asyncapi/__tests__/asyncapi-server-not-example-com.test.ts, packages/rulesets/src/asyncapi/__tests__/asyncapi-servers.test.ts, packages/rulesets/src/asyncapi/__tests__/asyncapi-tag-description.test.ts, packages/rulesets/src/asyncapi/__tests__/asyncapi-tags-alphabetical.test.ts, packages/rulesets/src/asyncapi/__tests__/asyncapi-tags.test.ts, packages/rulesets/src/asyncapi/index.ts, test-harness/scenarios/asyncapi2-streetlights.scenario, tsconfig.json
Related to #1619 
**Checklist**
=> feat(rulesets): more consistent messages in AsyncAPI ruleset

test-harness/index.ts
Hopefully fixes https://app.circleci.com/pipelines/github/stoplightio/spectral/6596/workflows/10bb9be8-7603-42e5-a2db-1c48da25f1be/jobs/19804.
This one is also not particularly common, but occurs from time to time.
Since we have these automated releases now, it makes sense to address it to ensure the release is not blocked by that random failure.
**Checklist**
=> chore(test-harness): smarter date replacement 

package.json, yarn.lock
Trying to fix semantic-releases https://app.circleci.com/pipelines/github/stoplightio/spectral/6684/workflows/860c7065-508d-4dcc-bf3f-7b73fa10552b/jobs/20297
**Checklist**
=> chore(repo): added semantic-release git plugin

package.json
Disables husky when releasing with semantic-release
=> fix(repo): disable husky on release

package.json
Remove version added by semantic-release
=> chore(repo): remove root version

packages/cli/package.json, packages/cli/src/services/linter/utils/getResolver.ts, packages/core/package.json, packages/formats/package.json, packages/functions/package.json, packages/ruleset-migrator/package.json, packages/rulesets/package.json, yarn.lock
=> feat(parsers): initial release

.circleci/config.yml
=> build(repo): do not execute "npm version from-git"
